declare var _default: {
    '--ease-1': string;
    '--ease-2': string;
    '--ease-3': string;
    '--ease-4': string;
    '--ease-5': string;
    '--ease-in-1': string;
    '--ease-in-2': string;
    '--ease-in-3': string;
    '--ease-in-4': string;
    '--ease-in-5': string;
    '--ease-out-1': string;
    '--ease-out-2': string;
    '--ease-out-3': string;
    '--ease-out-4': string;
    '--ease-out-5': string;
    '--ease-in-out-1': string;
    '--ease-in-out-2': string;
    '--ease-in-out-3': string;
    '--ease-in-out-4': string;
    '--ease-in-out-5': string;
    '--ease-elastic-1': string;
    '--ease-elastic-2': string;
    '--ease-elastic-3': string;
    '--ease-elastic-4': string;
    '--ease-elastic-5': string;
    '--ease-squish-1': string;
    '--ease-squish-2': string;
    '--ease-squish-3': string;
    '--ease-squish-4': string;
    '--ease-squish-5': string;
    '--ease-step-1': string;
    '--ease-step-2': string;
    '--ease-step-3': string;
    '--ease-step-4': string;
    '--ease-step-5': string;
};
export default _default;
