export const Gray: {
    '--gray-0-hsl': string;
    '--gray-1-hsl': string;
    '--gray-2-hsl': string;
    '--gray-3-hsl': string;
    '--gray-4-hsl': string;
    '--gray-5-hsl': string;
    '--gray-6-hsl': string;
    '--gray-7-hsl': string;
    '--gray-8-hsl': string;
    '--gray-9-hsl': string;
};
export const Red: {
    '--red-0-hsl': string;
    '--red-1-hsl': string;
    '--red-2-hsl': string;
    '--red-3-hsl': string;
    '--red-4-hsl': string;
    '--red-5-hsl': string;
    '--red-6-hsl': string;
    '--red-7-hsl': string;
    '--red-8-hsl': string;
    '--red-9-hsl': string;
};
export const Pink: {
    '--pink-0-hsl': string;
    '--pink-1-hsl': string;
    '--pink-2-hsl': string;
    '--pink-3-hsl': string;
    '--pink-4-hsl': string;
    '--pink-5-hsl': string;
    '--pink-6-hsl': string;
    '--pink-7-hsl': string;
    '--pink-8-hsl': string;
    '--pink-9-hsl': string;
};
export const Grape: {
    '--grape-0-hsl': string;
    '--grape-1-hsl': string;
    '--grape-2-hsl': string;
    '--grape-3-hsl': string;
    '--grape-4-hsl': string;
    '--grape-5-hsl': string;
    '--grape-6-hsl': string;
    '--grape-7-hsl': string;
    '--grape-8-hsl': string;
    '--grape-9-hsl': string;
};
export const Violet: {
    '--violet-0-hsl': string;
    '--violet-1-hsl': string;
    '--violet-2-hsl': string;
    '--violet-3-hsl': string;
    '--violet-4-hsl': string;
    '--violet-5-hsl': string;
    '--violet-6-hsl': string;
    '--violet-7-hsl': string;
    '--violet-8-hsl': string;
    '--violet-9-hsl': string;
};
export const Indigo: {
    '--indigo-0-hsl': string;
    '--indigo-1-hsl': string;
    '--indigo-2-hsl': string;
    '--indigo-3-hsl': string;
    '--indigo-4-hsl': string;
    '--indigo-5-hsl': string;
    '--indigo-6-hsl': string;
    '--indigo-7-hsl': string;
    '--indigo-8-hsl': string;
    '--indigo-9-hsl': string;
};
export const Blue: {
    '--blue-0-hsl': string;
    '--blue-1-hsl': string;
    '--blue-2-hsl': string;
    '--blue-3-hsl': string;
    '--blue-4-hsl': string;
    '--blue-5-hsl': string;
    '--blue-6-hsl': string;
    '--blue-7-hsl': string;
    '--blue-8-hsl': string;
    '--blue-9-hsl': string;
};
export const Cyan: {
    '--cyan-0-hsl': string;
    '--cyan-1-hsl': string;
    '--cyan-2-hsl': string;
    '--cyan-3-hsl': string;
    '--cyan-4-hsl': string;
    '--cyan-5-hsl': string;
    '--cyan-6-hsl': string;
    '--cyan-7-hsl': string;
    '--cyan-8-hsl': string;
    '--cyan-9-hsl': string;
};
export const Teal: {
    '--teal-0-hsl': string;
    '--teal-1-hsl': string;
    '--teal-2-hsl': string;
    '--teal-3-hsl': string;
    '--teal-4-hsl': string;
    '--teal-5-hsl': string;
    '--teal-6-hsl': string;
    '--teal-7-hsl': string;
    '--teal-8-hsl': string;
    '--teal-9-hsl': string;
};
export const Green: {
    '--green-0-hsl': string;
    '--green-1-hsl': string;
    '--green-2-hsl': string;
    '--green-3-hsl': string;
    '--green-4-hsl': string;
    '--green-5-hsl': string;
    '--green-6-hsl': string;
    '--green-7-hsl': string;
    '--green-8-hsl': string;
    '--green-9-hsl': string;
};
export const Lime: {
    '--lime-0-hsl': string;
    '--lime-1-hsl': string;
    '--lime-2-hsl': string;
    '--lime-3-hsl': string;
    '--lime-4-hsl': string;
    '--lime-5-hsl': string;
    '--lime-6-hsl': string;
    '--lime-7-hsl': string;
    '--lime-8-hsl': string;
    '--lime-9-hsl': string;
};
export const Yellow: {
    '--yellow-0-hsl': string;
    '--yellow-1-hsl': string;
    '--yellow-2-hsl': string;
    '--yellow-3-hsl': string;
    '--yellow-4-hsl': string;
    '--yellow-5-hsl': string;
    '--yellow-6-hsl': string;
    '--yellow-7-hsl': string;
    '--yellow-8-hsl': string;
    '--yellow-9-hsl': string;
};
export const Orange: {
    '--orange-0-hsl': string;
    '--orange-1-hsl': string;
    '--orange-2-hsl': string;
    '--orange-3-hsl': string;
    '--orange-4-hsl': string;
    '--orange-5-hsl': string;
    '--orange-6-hsl': string;
    '--orange-7-hsl': string;
    '--orange-8-hsl': string;
    '--orange-9-hsl': string;
};
export default ColorsHSL;
declare const ColorsHSL: {
    '--orange-0-hsl': string;
    '--orange-1-hsl': string;
    '--orange-2-hsl': string;
    '--orange-3-hsl': string;
    '--orange-4-hsl': string;
    '--orange-5-hsl': string;
    '--orange-6-hsl': string;
    '--orange-7-hsl': string;
    '--orange-8-hsl': string;
    '--orange-9-hsl': string;
    '--yellow-0-hsl': string;
    '--yellow-1-hsl': string;
    '--yellow-2-hsl': string;
    '--yellow-3-hsl': string;
    '--yellow-4-hsl': string;
    '--yellow-5-hsl': string;
    '--yellow-6-hsl': string;
    '--yellow-7-hsl': string;
    '--yellow-8-hsl': string;
    '--yellow-9-hsl': string;
    '--lime-0-hsl': string;
    '--lime-1-hsl': string;
    '--lime-2-hsl': string;
    '--lime-3-hsl': string;
    '--lime-4-hsl': string;
    '--lime-5-hsl': string;
    '--lime-6-hsl': string;
    '--lime-7-hsl': string;
    '--lime-8-hsl': string;
    '--lime-9-hsl': string;
    '--green-0-hsl': string;
    '--green-1-hsl': string;
    '--green-2-hsl': string;
    '--green-3-hsl': string;
    '--green-4-hsl': string;
    '--green-5-hsl': string;
    '--green-6-hsl': string;
    '--green-7-hsl': string;
    '--green-8-hsl': string;
    '--green-9-hsl': string;
    '--teal-0-hsl': string;
    '--teal-1-hsl': string;
    '--teal-2-hsl': string;
    '--teal-3-hsl': string;
    '--teal-4-hsl': string;
    '--teal-5-hsl': string;
    '--teal-6-hsl': string;
    '--teal-7-hsl': string;
    '--teal-8-hsl': string;
    '--teal-9-hsl': string;
    '--cyan-0-hsl': string;
    '--cyan-1-hsl': string;
    '--cyan-2-hsl': string;
    '--cyan-3-hsl': string;
    '--cyan-4-hsl': string;
    '--cyan-5-hsl': string;
    '--cyan-6-hsl': string;
    '--cyan-7-hsl': string;
    '--cyan-8-hsl': string;
    '--cyan-9-hsl': string;
    '--blue-0-hsl': string;
    '--blue-1-hsl': string;
    '--blue-2-hsl': string;
    '--blue-3-hsl': string;
    '--blue-4-hsl': string;
    '--blue-5-hsl': string;
    '--blue-6-hsl': string;
    '--blue-7-hsl': string;
    '--blue-8-hsl': string;
    '--blue-9-hsl': string;
    '--indigo-0-hsl': string;
    '--indigo-1-hsl': string;
    '--indigo-2-hsl': string;
    '--indigo-3-hsl': string;
    '--indigo-4-hsl': string;
    '--indigo-5-hsl': string;
    '--indigo-6-hsl': string;
    '--indigo-7-hsl': string;
    '--indigo-8-hsl': string;
    '--indigo-9-hsl': string;
    '--violet-0-hsl': string;
    '--violet-1-hsl': string;
    '--violet-2-hsl': string;
    '--violet-3-hsl': string;
    '--violet-4-hsl': string;
    '--violet-5-hsl': string;
    '--violet-6-hsl': string;
    '--violet-7-hsl': string;
    '--violet-8-hsl': string;
    '--violet-9-hsl': string;
    '--grape-0-hsl': string;
    '--grape-1-hsl': string;
    '--grape-2-hsl': string;
    '--grape-3-hsl': string;
    '--grape-4-hsl': string;
    '--grape-5-hsl': string;
    '--grape-6-hsl': string;
    '--grape-7-hsl': string;
    '--grape-8-hsl': string;
    '--grape-9-hsl': string;
    '--pink-0-hsl': string;
    '--pink-1-hsl': string;
    '--pink-2-hsl': string;
    '--pink-3-hsl': string;
    '--pink-4-hsl': string;
    '--pink-5-hsl': string;
    '--pink-6-hsl': string;
    '--pink-7-hsl': string;
    '--pink-8-hsl': string;
    '--pink-9-hsl': string;
    '--red-0-hsl': string;
    '--red-1-hsl': string;
    '--red-2-hsl': string;
    '--red-3-hsl': string;
    '--red-4-hsl': string;
    '--red-5-hsl': string;
    '--red-6-hsl': string;
    '--red-7-hsl': string;
    '--red-8-hsl': string;
    '--red-9-hsl': string;
    '--gray-0-hsl': string;
    '--gray-1-hsl': string;
    '--gray-2-hsl': string;
    '--gray-3-hsl': string;
    '--gray-4-hsl': string;
    '--gray-5-hsl': string;
    '--gray-6-hsl': string;
    '--gray-7-hsl': string;
    '--gray-8-hsl': string;
    '--gray-9-hsl': string;
};
